### PR TITLE
Update Hoa's logo

### LINKED ISSUE #4: Update Hoa's logo
Please :-). New logo is here: http://static.hoa-project.net/Image/Hoa.svg.

### PR DESCRIPTION
**Pull request by K-Phoen**
Fixes #4

### CODE REVIEW

**Comment by Hywan** [comment]
Do we need a release?

**Comment by K-Phoen** [comment]
Yep, a _patch_ release would be fine :)

**Comment by Hywan** [comment]
Do you know how to do that?

**Comment by K-Phoen** [comment]
I just noticed that there is no release for this bundle so we don't have to do anything (except maybe release the first stable version?)

**Comment by Hywan** [comment]
@K-Phoen: You have to run create a tag and then push it, but on `git.hoa-project.net`. Are you familiar with the release/commit process?

**Pull request merged**
