### PR TITLE
Updated dependency version

### PR DESCRIPTION
**Pull request by wakqasahmed**
Works as expected, tested on akeneo

### CODE REVIEW

**Comment by Hywan** [comment]
It looks good. Don't know if there are other implications. I will try to merge it today!

**Comment by wakqasahmed** [comment]
Thanks, it would be nice since right now i am using my patch as a workaround.

**Comment by Hywan** [comment]
Thank you very much @wakqasahmed :-).

**Comment by Hywan** [comment]
Welcome on board, https://hoa-project.net/En/Community.html \o/

**Comment by Hywan** [comment]
You even have a release, https://github.com/hoaproject/Contributions-Symfony-RulerBundle/releases :-].

**Comment by wakqasahmed** [comment]
Thanks for the appreciation. Open-source community rocks!

**Comment by Hywan** [comment]
If you heard of any events in Dubai where you think we can fit, please, ping us :-). Never gone there, and would love too!

**Pull request merged**
