### PR TITLE
Update Hoa's logo

### LINKED ISSUE #4: Update Hoa's logo
Please :-). New logo is here: http://static.hoa-project.net/Image/Hoa.svg.

### PR DESCRIPTION
**Pull request by K-Phoen**
Fixes #4

### CODE REVIEW

**Comment by Hywan** [comment]
Why @Bhoat did close this PR? Hmm.

**Comment by Hywan** [comment]
I cannot re-open it. @K-Phoen Can you try to know why please?

**Comment by Hywan** [comment]
Maybe the logo deserves a white background, because we can't see it correctly.

**Comment by K-Phoen** [comment]
We can not re-open it since @Bhoat deleted the `update-logo` branch :)

Not sure it's much better in white…
hoa_white

**Comment by Hywan** [comment]
Add left and right margins.

**Comment by Hywan** [comment]
@K-Phoen It's better to push the branch on your fork instead of this repository :-).

**Comment by K-Phoen** [comment]
Would something like this be better?

profiler
toolbar

**Comment by Hywan** [comment]
Perfect :+1:!

**Pull request closed without merging**
